name: Build Aizen APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: 0

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt -y install automake libltdl-dev

      - name: Check Buildozer
        run: |
          buildozer --version

      - name: Prepare Android SDK, NDK and python-for-android
        run: |
          sed -i.bak \
            "s/# android.accept_sdk_license = False/android.accept_sdk_license = True/" \
            buildozer.spec

          buildozer android p4a -- --help

      - name: Build Android APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Aizen-APK
          path: bin/*.apk
          if-no-files-found: error
